//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APKToolGUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APKToolGUI.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligning.
        /// </summary>
        internal static string Aligning {
            get {
                return ResourceManager.GetString("Aligning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done!.
        /// </summary>
        internal static string AllDone {
            get {
                return ResourceManager.GetString("AllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndroidManifest.xml does not exist.
        /// </summary>
        internal static string AndroidManifestNotExist {
            get {
                return ResourceManager.GetString("AndroidManifestNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK Selected:.
        /// </summary>
        internal static string APKSelected {
            get {
                return ResourceManager.GetString("APKSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apktool version.
        /// </summary>
        internal static string APKToolVersion {
            get {
                return ResourceManager.GetString("APKToolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baksmali.
        /// </summary>
        internal static string Baksmali {
            get {
                return ResourceManager.GetString("Baksmali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t detect apktool version..
        /// </summary>
        internal static string CantDetectApktoolVersion {
            get {
                return ResourceManager.GetString("CantDetectApktoolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed target SDK to 29.
        /// </summary>
        internal static string ChangedTargetSdkTo29 {
            get {
                return ResourceManager.GetString("ChangedTargetSdkTo29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        internal static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Framework.
        /// </summary>
        internal static string ClearingFramework {
            get {
                return ResourceManager.GetString("ClearingFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile APK.
        /// </summary>
        internal static string CompileApk {
            get {
                return ResourceManager.GetString("CompileApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemble DEX.
        /// </summary>
        internal static string CompileDex {
            get {
                return ResourceManager.GetString("CompileDex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling dex.
        /// </summary>
        internal static string CompilingDex {
            get {
                return ResourceManager.GetString("CompilingDex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling successfully completed. Output directory &quot;{0}&quot;.
        /// </summary>
        internal static string CompilingSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("CompilingSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file &quot;{0}&quot; to temp directory &quot;{1}&quot;.
        /// </summary>
        internal static string CopyFileToTemp {
            get {
                return ResourceManager.GetString("CopyFileToTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy decompiled apk folder &quot;{0}&quot; to temp directory &quot;{1}&quot;.
        /// </summary>
        internal static string CopyFolderToTemp {
            get {
                return ResourceManager.GetString("CopyFolderToTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Unsigned APK.
        /// </summary>
        internal static string CreateUnsignedApk {
            get {
                return ResourceManager.GetString("CreateUnsignedApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode.
        /// </summary>
        internal static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        internal static string Decode {
            get {
                return ResourceManager.GetString("Decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected decompilation directory could not be created because contains invalid characters..
        /// </summary>
        internal static string DecodeCouldNotCreate {
            get {
                return ResourceManager.GetString("DecodeCouldNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination directory &quot;{0}&quot; already exists. Enable &quot;Force delete destination directory&quot; if you want to overwrite it..
        /// </summary>
        internal static string DecodeDesDirExists {
            get {
                return ResourceManager.GetString("DecodeDesDirExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompilation directory not selected..
        /// </summary>
        internal static string DecodeDirNotSelected {
            get {
                return ResourceManager.GetString("DecodeDirNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected framework directory does not exist..
        /// </summary>
        internal static string DecodeSelectedFrameworkNotExist {
            get {
                return ResourceManager.GetString("DecodeSelectedFrameworkNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding.
        /// </summary>
        internal static string Decoding {
            get {
                return ResourceManager.GetString("Decoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompile APK.
        /// </summary>
        internal static string DecompileApk {
            get {
                return ResourceManager.GetString("DecompileApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompiled APK directory does not exist.
        /// </summary>
        internal static string DecompiledAPKNotExist {
            get {
                return ResourceManager.GetString("DecompiledAPKNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disassemble DEX.
        /// </summary>
        internal static string DecompileDex {
            get {
                return ResourceManager.GetString("DecompileDex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompiling all APK files.
        /// </summary>
        internal static string DecompilingAllApkFiles {
            get {
                return ResourceManager.GetString("DecompilingAllApkFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompiling dex.
        /// </summary>
        internal static string DecompilingDex {
            get {
                return ResourceManager.GetString("DecompilingDex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompiling successfully completed. Output directory &quot;{0}&quot;..
        /// </summary>
        internal static string DecompilingSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("DecompilingSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file &quot;{0}&quot;.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} detected as base.
        /// </summary>
        internal static string DetectedAsBase {
            get {
                return ResourceManager.GetString("DetectedAsBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} detected as split.
        /// </summary>
        internal static string DetectedAsSplit {
            get {
                return ResourceManager.GetString("DetectedAsSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &quot;{0}&quot; does not exist.
        /// </summary>
        internal static string DirNotExist {
            get {
                return ResourceManager.GetString("DirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want to install context menu?.
        /// </summary>
        internal static string DoYouRealyWantToInstallCM {
            get {
                return ResourceManager.GetString("DoYouRealyWantToInstallCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want to remove context menu?.
        /// </summary>
        internal static string DoYouRealyWantToRemoveCM {
            get {
                return ResourceManager.GetString("DoYouRealyWantToRemoveCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running as administrator. Drag &amp; drop is not supported.
        /// </summary>
        internal static string DragDropNotSupported {
            get {
                return ResourceManager.GetString("DragDropNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; drop is supported.
        /// </summary>
        internal static string DragDropSupported {
            get {
                return ResourceManager.GetString("DragDropSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error clearing framework.
        /// </summary>
        internal static string ErrorClearingFw {
            get {
                return ResourceManager.GetString("ErrorClearingFw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling failed.
        /// </summary>
        internal static string ErrorCompiling {
            get {
                return ResourceManager.GetString("ErrorCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompiling failed.
        /// </summary>
        internal static string ErrorDecompiling {
            get {
                return ResourceManager.GetString("ErrorDecompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error entering framework tag..
        /// </summary>
        internal static string ErrorEnteringFrameworkTag {
            get {
                return ResourceManager.GetString("ErrorEnteringFrameworkTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting APK infomation.
        /// </summary>
        internal static string ErrorGettingApkInfo {
            get {
                return ResourceManager.GetString("ErrorGettingApkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java is not installed or is installed incorrectly. Please install Java or set custom location in Settings.
        /// </summary>
        internal static string ErrorJavaDetect {
            get {
                return ResourceManager.GetString("ErrorJavaDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging failed.
        /// </summary>
        internal static string ErrorMerging {
            get {
                return ResourceManager.GetString("ErrorMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This directory is not an Android package.
        /// </summary>
        internal static string ErrorNotAnApk {
            get {
                return ResourceManager.GetString("ErrorNotAnApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading settings!.
        /// </summary>
        internal static string ErrorReadSettings {
            get {
                return ResourceManager.GetString("ErrorReadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings!.
        /// </summary>
        internal static string ErrorSaveSettings {
            get {
                return ResourceManager.GetString("ErrorSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file does not exist..
        /// </summary>
        internal static string ErrorSelectedFileNotExist {
            get {
                return ResourceManager.GetString("ErrorSelectedFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder does not exist..
        /// </summary>
        internal static string ErrorSelectedFolderNotExist {
            get {
                return ResourceManager.GetString("ErrorSelectedFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected output folder does not exist..
        /// </summary>
        internal static string ErrorSelectedOutputFolderNotExist {
            get {
                return ResourceManager.GetString("ErrorSelectedOutputFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error selecting framework directory..
        /// </summary>
        internal static string ErrorSelectingFrameworkDirectory {
            get {
                return ResourceManager.GetString("ErrorSelectingFrameworkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error selecting framework file. The file does not exist..
        /// </summary>
        internal static string ErrorSelectingFrameworkFile {
            get {
                return ResourceManager.GetString("ErrorSelectingFrameworkFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing failed..
        /// </summary>
        internal static string ErrorSigning {
            get {
                return ResourceManager.GetString("ErrorSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error update checking:.
        /// </summary>
        internal static string ErrorUpdateChecking {
            get {
                return ResourceManager.GetString("ErrorUpdateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse version.
        /// </summary>
        internal static string ErrorVersionParsing {
            get {
                return ResourceManager.GetString("ErrorVersionParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipaligning failed.
        /// </summary>
        internal static string ErrorZipalign {
            get {
                return ResourceManager.GetString("ErrorZipalign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable file.
        /// </summary>
        internal static string ExecutableFile {
            get {
                return ResourceManager.GetString("ExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting all APK files.
        /// </summary>
        internal static string ExtractingAllApkFiles {
            get {
                return ResourceManager.GetString("ExtractingAllApkFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract original signature.
        /// </summary>
        internal static string ExtractOrigSignature {
            get {
                return ResourceManager.GetString("ExtractOrigSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed AndroidManifest.xml.
        /// </summary>
        internal static string FixAndroidManifest {
            get {
                return ResourceManager.GetString("FixAndroidManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist.
        /// </summary>
        internal static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework cache cleared.
        /// </summary>
        internal static string FrameworkCacheCleared {
            get {
                return ResourceManager.GetString("FrameworkCacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework directory does not exist.
        /// </summary>
        internal static string FrameworkDirNotExist {
            get {
                return ResourceManager.GetString("FrameworkDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Framework installation is not started..
        /// </summary>
        internal static string FrameworkInstallationNotStarted {
            get {
                return ResourceManager.GetString("FrameworkInstallationNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework has been installed successfully.
        /// </summary>
        internal static string FrameworkInstalled {
            get {
                return ResourceManager.GetString("FrameworkInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get APK Info.
        /// </summary>
        internal static string GetApkInfo {
            get {
                return ResourceManager.GetString("GetApkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input directory: {0}.
        /// </summary>
        internal static string InputDirectory {
            get {
                return ResourceManager.GetString("InputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file: {0}.
        /// </summary>
        internal static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install framework.
        /// </summary>
        internal static string InstallFramework {
            get {
                return ResourceManager.GetString("InstallFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing framework.
        /// </summary>
        internal static string InstallingFramework {
            get {
                return ResourceManager.GetString("InstallingFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main activity found in &quot;{0}&quot;.
        /// </summary>
        internal static string MainActivityFound {
            get {
                return ResourceManager.GetString("MainActivityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find MainActivity. Please find it manually.
        /// </summary>
        internal static string MainActivityNotFoundPleaseFindManually {
            get {
                return ResourceManager.GetString("MainActivityNotFoundPleaseFindManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge finished. Moving directory to &quot;{0}&quot;.
        /// </summary>
        internal static string MergeFinishedMoveDir {
            get {
                return ResourceManager.GetString("MergeFinishedMoveDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging APK.
        /// </summary>
        internal static string MergingApk {
            get {
                return ResourceManager.GetString("MergingApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging APK using APKEditor.jar.
        /// </summary>
        internal static string MergingApkEditor {
            get {
                return ResourceManager.GetString("MergingApkEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to META-INF folder does not exist. Skipped.
        /// </summary>
        internal static string MetainfNotExist {
            get {
                return ResourceManager.GetString("MetainfNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move temp folder &quot;{0}&quot; to output directory &quot;{1}&quot;.
        /// </summary>
        internal static string MoveTempApkFileToOutput {
            get {
                return ResourceManager.GetString("MoveTempApkFileToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move temp apk &quot;{0}&quot; to output directory &quot;{1}&quot;.
        /// </summary>
        internal static string MoveTempApkToOutput {
            get {
                return ResourceManager.GetString("MoveTempApkToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving base directory to &quot;{0}&quot;.
        /// </summary>
        internal static string MovingBasedirectory {
            get {
                return ResourceManager.GetString("MovingBasedirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the changes to take effect you must restart the program. You want to do it now?.
        /// </summary>
        internal static string NeedRestart {
            get {
                return ResourceManager.GetString("NeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is not a decompiled APK.
        /// </summary>
        internal static string NotDecompiledApk {
            get {
                return ResourceManager.GetString("NotDecompiledApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is not a decompiled DEX.
        /// </summary>
        internal static string NotDecompiledDex {
            get {
                return ResourceManager.GetString("NotDecompiledDex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing APK Info....
        /// </summary>
        internal static string ParsingApkInfo {
            get {
                return ResourceManager.GetString("ParsingApkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed all ApkTool dummies.
        /// </summary>
        internal static string RemoveApkToolDummies {
            get {
                return ResourceManager.GetString("RemoveApkToolDummies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required files are missing.
        /// </summary>
        internal static string RequiredFilesMissing {
            get {
                return ResourceManager.GetString("RequiredFilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is set. Do you want to restart the application?.
        /// </summary>
        internal static string SetLanguageRestartApplication {
            get {
                return ResourceManager.GetString("SetLanguageRestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign APK.
        /// </summary>
        internal static string SignApk {
            get {
                return ResourceManager.GetString("SignApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing.
        /// </summary>
        internal static string Signing {
            get {
                return ResourceManager.GetString("Signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file not found..
        /// </summary>
        internal static string SignInputFileNotFound {
            get {
                return ResourceManager.GetString("SignInputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key not found..
        /// </summary>
        internal static string SignPrivateKeyNotFound {
            get {
                return ResourceManager.GetString("SignPrivateKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key not found..
        /// </summary>
        internal static string SignPublicKeyNotFound {
            get {
                return ResourceManager.GetString("SignPublicKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing successfully completed. File saved to &quot;{0}&quot;..
        /// </summary>
        internal static string SignSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("SignSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smali.
        /// </summary>
        internal static string Smali {
            get {
                return ResourceManager.GetString("Smali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System language.
        /// </summary>
        internal static string SystemLanguage {
            get {
                return ResourceManager.GetString("SystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp directory: &quot;{0}&quot;.
        /// </summary>
        internal static string TempDirectory {
            get {
                return ResourceManager.GetString("TempDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        internal static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available. Do you want to update?.
        /// </summary>
        internal static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update is available..
        /// </summary>
        internal static string UpdateNoUpdates {
            get {
                return ResourceManager.GetString("UpdateNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding folder not selected!.
        /// </summary>
        internal static string WarningDecodingFolderNotSelected {
            get {
                return ResourceManager.GetString("WarningDecodingFolderNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File for decoding not selected!.
        /// </summary>
        internal static string WarningFileForDecodingNotSelected {
            get {
                return ResourceManager.GetString("WarningFileForDecodingNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File for signing not selected!.
        /// </summary>
        internal static string WarningFileForSigningNotSelected {
            get {
                return ResourceManager.GetString("WarningFileForSigningNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework not selected!.
        /// </summary>
        internal static string WarningFrameworkNotSelected {
            get {
                return ResourceManager.GetString("WarningFrameworkNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipalign.
        /// </summary>
        internal static string Zipalign {
            get {
                return ResourceManager.GetString("Zipalign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipalign APK.
        /// </summary>
        internal static string ZipalignApk {
            get {
                return ResourceManager.GetString("ZipalignApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipalign successfully completed. File saved to &quot;{0}&quot;.
        /// </summary>
        internal static string ZipalignFileSavedTo {
            get {
                return ResourceManager.GetString("ZipalignFileSavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP archives.
        /// </summary>
        internal static string ZIPArchives {
            get {
                return ResourceManager.GetString("ZIPArchives", resourceCulture);
            }
        }
    }
}
