//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APKToolGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Decode_NoSrc {
            get {
                return ((bool)(this["MAIN_Decode_NoSrc"]));
            }
            set {
                this["MAIN_Decode_NoSrc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Decode_NoRes {
            get {
                return ((bool)(this["MAIN_Decode_NoRes"]));
            }
            set {
                this["MAIN_Decode_NoRes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Decode_Force {
            get {
                return ((bool)(this["MAIN_Decode_Force"]));
            }
            set {
                this["MAIN_Decode_Force"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Decode_UseFramework {
            get {
                return ((bool)(this["MAIN_Decode_UseFramework"]));
            }
            set {
                this["MAIN_Decode_UseFramework"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Build_ForceAll {
            get {
                return ((bool)(this["MAIN_Build_ForceAll"]));
            }
            set {
                this["MAIN_Build_ForceAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MAIN_Decode_InputAppPath {
            get {
                return ((string)(this["MAIN_Decode_InputAppPath"]));
            }
            set {
                this["MAIN_Decode_InputAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MAIN_Decode_FrameDir {
            get {
                return ((string)(this["MAIN_Decode_FrameDir"]));
            }
            set {
                this["MAIN_Decode_FrameDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MAIN_BuildProjectDir {
            get {
                return ((string)(this["MAIN_BuildProjectDir"]));
            }
            set {
                this["MAIN_BuildProjectDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MAIN_InstallFramework_InputFramePath {
            get {
                return ((string)(this["MAIN_InstallFramework_InputFramePath"]));
            }
            set {
                this["MAIN_InstallFramework_InputFramePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MAIN_SIGN_InputFile {
            get {
                return ((string)(this["MAIN_SIGN_InputFile"]));
            }
            set {
                this["MAIN_SIGN_InputFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MAIN_SIGN_OutputFile {
            get {
                return ((string)(this["MAIN_SIGN_OutputFile"]));
            }
            set {
                this["MAIN_SIGN_OutputFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Build_UseAapt {
            get {
                return ((bool)(this["MAIN_Build_UseAapt"]));
            }
            set {
                this["MAIN_Build_UseAapt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MAIN_Build_AaptPath {
            get {
                return ((string)(this["MAIN_Build_AaptPath"]));
            }
            set {
                this["MAIN_Build_AaptPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public string Culture {
            get {
                return ((string)(this["Culture"]));
            }
            set {
                this["Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string JavaExe {
            get {
                return ((string)(this["JavaExe"]));
            }
            set {
                this["JavaExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastUpdateCheck {
            get {
                return ((global::System.DateTime)(this["LastUpdateCheck"]));
            }
            set {
                this["LastUpdateCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdateAtStartup {
            get {
                return ((bool)(this["CheckForUpdateAtStartup"]));
            }
            set {
                this["CheckForUpdateAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearLogBeforeAction {
            get {
                return ((bool)(this["ClearLogBeforeAction"]));
            }
            set {
                this["ClearLogBeforeAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BUILD_ForceAll {
            get {
                return ((bool)(this["BUILD_ForceAll"]));
            }
            set {
                this["BUILD_ForceAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BUILD_CustomAapt {
            get {
                return ((bool)(this["BUILD_CustomAapt"]));
            }
            set {
                this["BUILD_CustomAapt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string BUILD_AaptPath {
            get {
                return ((string)(this["BUILD_AaptPath"]));
            }
            set {
                this["BUILD_AaptPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DECOMPILE_NoRes {
            get {
                return ((bool)(this["DECOMPILE_NoRes"]));
            }
            set {
                this["DECOMPILE_NoRes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DECOMPILE_NoSrc {
            get {
                return ((bool)(this["DECOMPILE_NoSrc"]));
            }
            set {
                this["DECOMPILE_NoSrc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DECOMPILE_Force {
            get {
                return ((bool)(this["DECOMPILE_Force"]));
            }
            set {
                this["DECOMPILE_Force"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DECOMPILE_UseFramework {
            get {
                return ((bool)(this["DECOMPILE_UseFramework"]));
            }
            set {
                this["DECOMPILE_UseFramework"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BUILD_CopyOriginal {
            get {
                return ((bool)(this["BUILD_CopyOriginal"]));
            }
            set {
                this["BUILD_CopyOriginal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BUILD_UseFramework {
            get {
                return ((bool)(this["BUILD_UseFramework"]));
            }
            set {
                this["BUILD_UseFramework"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string BUILD_FrameworkPath {
            get {
                return ((string)(this["BUILD_FrameworkPath"]));
            }
            set {
                this["BUILD_FrameworkPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DECOMPILE_KeepBrokenResource {
            get {
                return ((bool)(this["DECOMPILE_KeepBrokenResource"]));
            }
            set {
                this["DECOMPILE_KeepBrokenResource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DECOMPILE_MatchOriginal {
            get {
                return ((bool)(this["DECOMPILE_MatchOriginal"]));
            }
            set {
                this["DECOMPILE_MatchOriginal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Decode_MatchOriginal {
            get {
                return ((bool)(this["MAIN_Decode_MatchOriginal"]));
            }
            set {
                this["MAIN_Decode_MatchOriginal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Decode_KeepBrokenRes {
            get {
                return ((bool)(this["MAIN_Decode_KeepBrokenRes"]));
            }
            set {
                this["MAIN_Decode_KeepBrokenRes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Build_CopyOriginal {
            get {
                return ((bool)(this["MAIN_Build_CopyOriginal"]));
            }
            set {
                this["MAIN_Build_CopyOriginal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MAIN_Build_FrameDir {
            get {
                return ((string)(this["MAIN_Build_FrameDir"]));
            }
            set {
                this["MAIN_Build_FrameDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Build_UseFramework {
            get {
                return ((bool)(this["MAIN_Build_UseFramework"]));
            }
            set {
                this["MAIN_Build_UseFramework"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Decode_UseOutputDir {
            get {
                return ((bool)(this["MAIN_Decode_UseOutputDir"]));
            }
            set {
                this["MAIN_Decode_UseOutputDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MAIN_Decode_OutputDir {
            get {
                return ((string)(this["MAIN_Decode_OutputDir"]));
            }
            set {
                this["MAIN_Decode_OutputDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Build_UseOutputAppPath {
            get {
                return ((bool)(this["MAIN_Build_UseOutputAppPath"]));
            }
            set {
                this["MAIN_Build_UseOutputAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAIN_Build_OutputAppPath {
            get {
                return ((string)(this["MAIN_Build_OutputAppPath"]));
            }
            set {
                this["MAIN_Build_OutputAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAIN_Build_InputDir {
            get {
                return ((string)(this["MAIN_Build_InputDir"]));
            }
            set {
                this["MAIN_Build_InputDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_InstallFramework_UseFrameDir {
            get {
                return ((bool)(this["MAIN_InstallFramework_UseFrameDir"]));
            }
            set {
                this["MAIN_InstallFramework_UseFrameDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_InstallFramework_UseTag {
            get {
                return ((bool)(this["MAIN_InstallFramework_UseTag"]));
            }
            set {
                this["MAIN_InstallFramework_UseTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAIN_InstallFramework_Tag {
            get {
                return ((string)(this["MAIN_InstallFramework_Tag"]));
            }
            set {
                this["MAIN_InstallFramework_Tag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAIN_InstallFramework_FrameDir {
            get {
                return ((string)(this["MAIN_InstallFramework_FrameDir"]));
            }
            set {
                this["MAIN_InstallFramework_FrameDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public decimal MAIN_Zipalign_AlignmentInBytes {
            get {
                return ((decimal)(this["MAIN_Zipalign_AlignmentInBytes"]));
            }
            set {
                this["MAIN_Zipalign_AlignmentInBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Zipalign_OverwriteOutputFile {
            get {
                return ((bool)(this["MAIN_Zipalign_OverwriteOutputFile"]));
            }
            set {
                this["MAIN_Zipalign_OverwriteOutputFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Zipalign_CheckOnly {
            get {
                return ((bool)(this["MAIN_Zipalign_CheckOnly"]));
            }
            set {
                this["MAIN_Zipalign_CheckOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Zipalign_Verbose {
            get {
                return ((bool)(this["MAIN_Zipalign_Verbose"]));
            }
            set {
                this["MAIN_Zipalign_Verbose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAIN_Zipalign_OutputFile {
            get {
                return ((string)(this["MAIN_Zipalign_OutputFile"]));
            }
            set {
                this["MAIN_Zipalign_OutputFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAIN_Zipalign_InputFile {
            get {
                return ((string)(this["MAIN_Zipalign_InputFile"]));
            }
            set {
                this["MAIN_Zipalign_InputFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_Zipalign_Recompress {
            get {
                return ((bool)(this["MAIN_Zipalign_Recompress"]));
            }
            set {
                this["MAIN_Zipalign_Recompress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bin\\testkey.x509.pem")]
        public string MAIN_SIGN_PublicKey {
            get {
                return ((string)(this["MAIN_SIGN_PublicKey"]));
            }
            set {
                this["MAIN_SIGN_PublicKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bin\\testkey.pk8")]
        public string MAIN_SIGN_PrivateKey {
            get {
                return ((string)(this["MAIN_SIGN_PrivateKey"]));
            }
            set {
                this["MAIN_SIGN_PrivateKey"] = value;
            }
        }
    }
}
