name: Feature request
description: Request a feature for APK Tool GUI
labels: enhancement
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: This is not a support issue or a question. For support, questions, or help, see [support links](https://github.com/AndnixSH/APKToolGUI/issues/new/choose).
          required: true
        - label: I performed a cursory search of the issue tracker on [APK Tool GUI](https://github.com/AndnixSH/APKToolGUI/issues?q=is%3Aissue) to avoid opening a duplicate issue
          required: true
        - label: I have read the [FAQ](https://github.com/AndnixSH/APKToolGUI#faq)
          required: true

  - type: textarea
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen. Not all features will be accepted
    validations:
      required: true

